### ISSUE TITLE
New way to Register user

### ISSUE THREAD

**Issue by Lapotor** [itpao25/ReporterGUIWeb#1]
Hey can you maybe implament that if you want to create an new User that you can couse between set password and send an register E-Mail.
So you don't know the Password of him.

**Comment by itpao25** [comment]
For the moment the new user can change him password using the user panel

**Comment by Lapotor** [comment]
where ?

**Comment by Lapotor** [comment]
where can i change the password as Helper ?

**Comment by itpao25** [comment]
In the list of all users (Manager user) you can click on user that you want edit.
Remember that you must be a administrator.

**Comment by Lapotor** [comment]
Yeah but the user should edit his password it self

**Comment by itpao25** [comment]
https://github.com/itpao25/ReporterGUIWeb/commit/6db863d7b50ed8a63a144d8c5933a0b9e10d1be6

**Comment by itpao25** [comment]
#https://github.com/itpao25/ReporterGUIWeb/commit/6db863d7b50ed8a63a144d8c5933a0b9e10d1be6

**Comment by itpao25** [comment]
#6db863d

**Comment by itpao25** [comment]
In this commit the problem should be solved: https://github.com/itpao25/ReporterGUIWeb/commit/6db863d7b50ed8a63a144d8c5933a0b9e10d1be6
You must replace the file "inc/groups.inc.php" with the last commit.
