### ISSUE TITLE
https://crafatar.com removed username support

### ISSUE THREAD

**Issue by ApertureDevelopment** [itpao25/ReporterGUIWeb#2]
Hello,

I noticed a mistake in the GUI. The website you are using to get the account avatar is no longer supporting usernames. They changed their system and just accept UUIDs from 2018 and further. 

You could fix that by adding a UUID field to the database, so when you create a account you can also enter the UUID to load the avatar. This could also be usefull for the case that a User changes his nickname.

**Comment by itpao25** [comment]
Hi, sorry about the two-year delay. Maybe it'll help someone.
To fix the problem of avatars it's necessary to update the config.php
Crafatar service doesn't support avatars using only the nickname, but needs a UUID, so for a quick update we change the service with Minotar.

So you need to go to the config.php file and edit the following lines:
`$config['urlServiceAvatar'] = "https://minotar.net/avatar/{username}";`


Service for avatar in menu
`$config['urlServiceAvatarMenu'] = "https://minotar.net/avatar/{username}";`
